//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cc.Utility {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ccEmailerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ccEmailerSettings defaultInstance = ((ccEmailerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ccEmailerSettings())));
        
        public static ccEmailerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user@myserver.com")]
        public string smtp_user {
            get {
                return ((string)(this["smtp_user"]));
            }
            set {
                this["smtp_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("myserver_password")]
        public string smtp_password {
            get {
                return ((string)(this["smtp_password"]));
            }
            set {
                this["smtp_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int smtp_port {
            get {
                return ((int)(this["smtp_port"]));
            }
            set {
                this["smtp_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool use_ssl {
            get {
                return ((bool)(this["use_ssl"]));
            }
            set {
                this["use_ssl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string smpt_server {
            get {
                return ((string)(this["smpt_server"]));
            }
            set {
                this["smpt_server"] = value;
            }
        }
    }
}
