//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccScreenSpy {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ccScreenSpySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ccScreenSpySettings defaultInstance = ((ccScreenSpySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ccScreenSpySettings())));
        
        public static ccScreenSpySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("you@youremail.com")]
        public string to_address {
            get {
                return ((string)(this["to_address"]));
            }
            set {
                this["to_address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("you@youremail.com")]
        public string from_address {
            get {
                return ((string)(this["from_address"]));
            }
            set {
                this["from_address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int capture_frequency {
            get {
                return ((int)(this["capture_frequency"]));
            }
            set {
                this["capture_frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string capture_directory {
            get {
                return ((string)(this["capture_directory"]));
            }
            set {
                this["capture_directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int captures_per_email {
            get {
                return ((int)(this["captures_per_email"]));
            }
            set {
                this["captures_per_email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Screen")]
        public string capture_subject {
            get {
                return ((string)(this["capture_subject"]));
            }
            set {
                this["capture_subject"] = value;
            }
        }
    }
}
